services:
  postgres:
    container_name: postgres_go_api
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/data/postgres
